import JSZip from 'jszip';
import type { AgentEdge, AgentNode, Project } from '../types/graph';

export interface ImportedProject extends Project {
  schemaVersion?: string;
  platformVersion?: string;
  description?: string;
}

export class ImportError extends Error {
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = 'ImportError';
  }
}

const SUPPORTED_SCHEMA_MAJOR = 1;

export async function importAgentZip(file: File): Promise<ImportedProject> {
  let zip: JSZip;
  try {
    zip = await JSZip.loadAsync(file);
  } catch (e) {
    throw new ImportError('File is not a valid ZIP archive', e);
  }

  const entry = zip.file('project.json');
  if (!entry) {
    throw new ImportError(
      "ZIP does not contain 'project.json'. Only ZIPs generated by this platform are importable.",
    );
  }

  let raw: string;
  try {
    raw = await entry.async('string');
  } catch (e) {
    throw new ImportError('Failed to read project.json from ZIP', e);
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    throw new ImportError('project.json is not valid JSON', e);
  }

  return normalizeProject(parsed);
}

function normalizeProject(raw: unknown): ImportedProject {
  if (!isObject(raw)) throw new ImportError('project.json must be a JSON object');

  const schemaVersion = typeof raw.schema_version === 'string' ? raw.schema_version : '1.0.0';
  assertSupportedSchema(schemaVersion);

  const name = typeof raw.name === 'string' && raw.name ? raw.name : 'imported-agent';
  const description = typeof raw.description === 'string' ? raw.description : undefined;
  const platformVersion = typeof raw.platform_version === 'string' ? raw.platform_version : undefined;

  const nodes = normalizeNodes(raw.nodes);
  const edges = normalizeEdges(raw.edges);

  validateReferences(nodes, edges);

  return {
    name,
    description,
    schemaVersion,
    platformVersion,
    nodes,
    edges,
  };
}

function normalizeNodes(raw: unknown): AgentNode[] {
  if (!Array.isArray(raw)) throw new ImportError("'nodes' must be an array");
  return raw.map((n, i) => {
    if (!isObject(n)) throw new ImportError(`nodes[${i}] is not an object`);
    if (typeof n.id !== 'string' || !n.id) throw new ImportError(`nodes[${i}].id is missing`);
    if (typeof n.type !== 'string') throw new ImportError(`nodes[${i}].type is missing`);

    const pos = isObject(n.position) ? n.position : {};
    return {
      id: n.id,
      type: n.type as AgentNode['type'],
      label: typeof n.label === 'string' ? n.label : n.type,
      position: {
        x: typeof pos.x === 'number' ? pos.x : 0,
        y: typeof pos.y === 'number' ? pos.y : 0,
      },
      config: isObject(n.config) ? (n.config as Record<string, unknown>) : {},
      ports: normalizePorts(n.ports),
    };
  });
}

function normalizePorts(raw: unknown): AgentNode['ports'] {
  if (!isObject(raw)) return { inputs: [], outputs: [] };
  const inputs = Array.isArray(raw.inputs) ? raw.inputs : [];
  const outputs = Array.isArray(raw.outputs) ? raw.outputs : [];
  return {
    inputs: inputs.map(normalizePort),
    outputs: outputs.map(normalizePort),
  };
}

function normalizePort(p: unknown): AgentNode['ports']['inputs'][number] {
  if (!isObject(p)) throw new ImportError('port entry is not an object');
  return {
    id: String(p.id ?? ''),
    name: String(p.name ?? p.id ?? ''),
    data_type: (typeof p.data_type === 'string' ? p.data_type : 'any') as AgentNode['ports']['inputs'][number]['data_type'],
    required: Boolean(p.required),
  };
}

function normalizeEdges(raw: unknown): AgentEdge[] {
  if (!Array.isArray(raw)) throw new ImportError("'edges' must be an array");
  return raw.map((e, i) => {
    if (!isObject(e)) throw new ImportError(`edges[${i}] is not an object`);
    const id = typeof e.id === 'string' && e.id ? e.id : `imported-edge-${i}`;
    return {
      id,
      source_node_id: String(e.source_node_id ?? ''),
      source_port_id: String(e.source_port_id ?? ''),
      target_node_id: String(e.target_node_id ?? ''),
      target_port_id: String(e.target_port_id ?? ''),
      data_type: (typeof e.data_type === 'string' ? e.data_type : 'any') as AgentEdge['data_type'],
    };
  });
}

function validateReferences(nodes: AgentNode[], edges: AgentEdge[]): void {
  const ids = new Set(nodes.map((n) => n.id));
  for (const e of edges) {
    if (!ids.has(e.source_node_id)) {
      throw new ImportError(`Edge ${e.id} references missing source node '${e.source_node_id}'`);
    }
    if (!ids.has(e.target_node_id)) {
      throw new ImportError(`Edge ${e.id} references missing target node '${e.target_node_id}'`);
    }
  }
}

function assertSupportedSchema(version: string): void {
  const major = parseInt(version.split('.')[0] ?? '0', 10);
  if (Number.isNaN(major)) {
    throw new ImportError(`Unrecognized schema_version '${version}'`);
  }
  if (major > SUPPORTED_SCHEMA_MAJOR) {
    throw new ImportError(
      `project.json schema_version ${version} is newer than this Studio supports (max v${SUPPORTED_SCHEMA_MAJOR}.x). Update the Studio to import.`,
    );
  }
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}
